module: CortexTrainer

wallet: 
  name: const
  hotkey: Tiberius

split: train
idx_bounds: [0, 1000]

dataset:
  module: commune.dataset.text.huggingface
  actor: {refresh: False, cpus: 1, wrap: True}


tokenizer:
  module: bittensor.tokenizer

receptor_pool:
  module: cortex.receptor_pool
  kwargs:
    max_active_receptors: 0


