


- name: Transfer and execute a script.
  hosts: all
  tasks:

  - name: Find out playbook's path
    shell: pwd
    register: playbook_path_output

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: "{{ lookup('env','HOME') }}/commune_ansible/src"
      dest: /tmp/commune_ansible
      owner: paperspace
      group: paperspace
      mode: '0644'


  - name: making ansible scripts executable
    ansible.builtin.shell: sudo docker exec -it commune bash -c "chmod +x /tmp/commune_ansible/"
    register: chmod_scripts

  - name: generating coldkey
    ansible.builtin.shell: sudo docker exec -it commune bash -c ". /tmp/commune_ansible/src/btcli_regen_coldkey.sh"
    register: coldkey_gen

  - name: generating hotkeys
    ansible.builtin.shell: sudo docker exec -it commune bash -c ". /tmp/commune_ansible/src/btcli_regen_hotkeys.sh /tmp"
    register: hotkey_gen

  - debug: msg="{{ hotkey_gen.stdout }}"
  - debug: msg="{{ hotkey_gen.stderr }}"