

- name: Transfer and execute a script.
  hosts: all
  tasks:
    - name: Copy and Execute the script 
      script: "{{ lookup('env','HOME') }}/commune_ansible/src/setup_commune.sh"
      register: hello

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: "{{ lookup('env','HOME') }}/commune_ansible/src"
      dest: /tmp/commune_ansible
      owner: paperspace
      group: paperspace
      mode: '0644'


  - name: making ansible scripts executable
    ansible.builtin.shell: sudo docker exec -it commune bash -c "chmod +x /tmp/commune_ansible/"
    register: chmod_scripts



  - name: generating coldkey
    ansible.builtin.shell: sudo docker exec -it commune bash -c ". /tmp/commune_ansible/src/btcli_regen_coldkey.sh"
    register: coldkey_gen

  - name: generating hotkeys
    ansible.builtin.shell: sudo docker exec -it commune bash -c ". /tmp/commune_ansible/src/btcli_regen_hotkeys.sh /tmp"
    register: hotkey_gen
    - name: make up to start commune if its not up already
      ansible.builtin.shell: sudo make up
      args:
        chdir: commune
      register: make_up

    - name: run
      ansible.builtin.shell: sudo docker exec -ti commune bash -c "python3 examples/register.py"
      args:
        chdir: commune  
      register: output
