- name: Transfer and execute a script.
  hosts: all
  tasks:
  - name: listing hotkeys
    ansible.builtin.shell: cd commune
  - name: Copy and Execute the script 
    script: "{{ lookup('env','HOME') }}/commune_ansible/src/install_python_env.sh"
    register: shell
  - debug: msg="{{ shell.stdout }}"
  - debug: msg="{{ shell.stderr }}"
