
models: model.
network: global
update: True
tokenizer: gptj
ensemble_mode: best
train: False
batch_size: 32
sequence_length: 256
refresh: False
dataset: dataset.bittensor
stats: {}
metric:  null
stats: {}
threshold: 4.0
max_stats_history: 100
namespace_update_interval: 100
alpha: 0.1
ma_keys: ['metric', 'weights']
max_models_per_call: 3
topk: 4096 
load: False
save: True
new_loop_per_forward: True
optimizer: 
  lr: 0.0001
hidden_size : 512
default_metric: 12
